services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      # Apple Silicon GPU acceleration
      - METAL_DEVICE=on
      - METAL_DEVICE_INDEX=0
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "127.0.0.1:11434:11434"  # Bind to localhost only
    restart: unless-stopped
    # Security hardening
    read_only: false  # Ollama needs write access
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
    networks:
      - hedge-fund-network

  hedge-fund:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: ai-hedge-fund
    depends_on:
      - ollama
    env_file:
      - ../.env
    command: python src/main.py --ticker AAPL,MSFT,NVDA
    environment:
      - PYTHONUNBUFFERED=1
      # For development only - in production, use HTTPS or a secure reverse proxy
      # Set ALLOW_PLAIN_OLLAMA=1 to suppress security warnings
      - OLLAMA_BASE_URL=http://ollama:11434
      - PYTHONPATH=/app
    # Security hardening
    read_only: false  # Application needs write access for caching
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
    networks:
      - hedge-fund-network

  hedge-fund-reasoning:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: ai-hedge-fund
    depends_on:
      - ollama
    env_file:
      - ../.env
    command: python src/main.py --ticker AAPL,MSFT,NVDA --show-reasoning
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_BASE_URL=http://ollama:11434
      - PYTHONPATH=/app
    # Security hardening
    read_only: false
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
    networks:
      - hedge-fund-network

  hedge-fund-ollama:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: ai-hedge-fund
    depends_on:
      - ollama
    env_file:
      - ../.env
    command: python src/main.py --ticker AAPL,MSFT,NVDA --ollama
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_BASE_URL=http://ollama:11434
      - PYTHONPATH=/app
    # Security hardening
    read_only: false
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
    networks:
      - hedge-fund-network

  backtester:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: ai-hedge-fund
    depends_on:
      - ollama
    env_file:
      - ../.env
    command: python src/backtester.py --ticker AAPL,MSFT,NVDA
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_BASE_URL=http://ollama:11434
      - PYTHONPATH=/app
    # Security hardening
    read_only: false
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
    networks:
      - hedge-fund-network

  backtester-ollama:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: ai-hedge-fund
    depends_on:
      - ollama
    env_file:
      - ../.env
    command: python src/backtester.py --ticker AAPL,MSFT,NVDA --ollama
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_BASE_URL=http://ollama:11434
      - PYTHONPATH=/app
    # Security hardening
    read_only: false
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
    networks:
      - hedge-fund-network

volumes:
  ollama_data:

networks:
  hedge-fund-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: hedge-fund-br
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
